### ISSUE TITLE
No support for variables input in aggregation pipeline

### ISSUE THREAD

**Issue by lpnc** [meln5674/grafana-mongodb-community-plugin#21]
Simply a very powerful feature not suported yet... 
...Or is it just me doing something wrong?

**Comment by yar2001** [comment]
According to my experiments, you can directly use `${xxx}` to denote the variable value. For example, if there is a variable called `uid` and is a number, the aggregate code should be:
```json
 {
    "$match": {
      "createdAt": {
        "$gte": {
          "$date": "${__from:date}"
        },
        "$lte": {
          "$date": "${__to:date}"
        }
      },
      "uid": ${uid:int}
    }
  }
  ```
Ignore the error in the json, when the plugin query to the backend, it will automatically replace ${uid:int} with number

**Comment by lpnc** [comment]
Nice, i will try that. Have you also been able to use mongo type such as ObjectId?
Writing : 
```
{
   "$match" : {
       "_id" : ObjectId(86h9855ho8553kcf270)
   }
}
```

Returns an error at `ObjectId` for me.

**Comment by meln5674** [comment]
This plugin supports [the standard grafana syntax for variables](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/), and will automatically handle inserting them into the JSON, as the above post describes. If you have a specific query that is not replacing variables, please post it here along with versions of grafana and the plugin, and I will try to reproduce. Otherwise, I will close this as not an issue in a few days if I don't hear back.
